version: '2'
services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ac_mediator
  nginx:
    build: ./docker/nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - web
    links:
      - web:web
      - flower:flower
  redis:
    image: redis
    ports:
      - "6379:6379"
  celery:
    build: .
    links:
      - redis:redis
    volumes:
      - .:/code
    command: celery worker -A ac_mediator --concurrency=100
    depends_on:
      - redis
  web:
    build: .
    environment:
      DOCKER_DB_HOST: db
      DOCKER_STATIC_ROOT: /static/
      DOCKER_DJANGO_BASE_URL: https://localhost
    expose:
      - "8000"
    links:
      - db:db
      - redis:redis
    volumes:
      - .:/code
      - /static/
      - /logs/
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && /usr/local/bin/gunicorn ac_mediator.wsgi:application -w 1 -b :8000 --reload --log-file=/logs/gunicorn.log --access-logfile=/logs/gunicorn-access.log"
    depends_on:
      - db
      - redis
  flower:  #  Django app to monitor Celery status
    build: ./docker/flower/
    environment:
      FLOWER_BASIC_AUTH: user:password
    command: flower --address=0.0.0.0 --port=5555 --broker=redis://redis --url_prefix=flower
    expose:
      - "5555"
    depends_on:
      - redis
