version: '2'
services:
  db:
    image: postgres:9.4
    env_file:
      - .env
  nginx:
    build: ./docker/nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - web
  redis:
    image: redis
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/code
      - /static/
      - /logs/
    command: bash -c "python manage.py migrate && /usr/local/bin/gunicorn ac_mediator.wsgi:application -w 1 -b :8000 --reload --log-file=/logs/gunicorn.log --access-logfile=/logs/gunicorn-access.log"
    depends_on:
      - db
      - redis
  celery:
    build: .
    env_file:
      - .env
    volumes:
      - .:/code
    command: celery worker -A ac_mediator --concurrency=100
    depends_on:
      - redis
  flower:  #  Django app to monitor Celery status
    build: ./docker/flower/
    env_file:
      - .env
    command: flower --address=0.0.0.0 --port=5555 --broker=redis://redis --url_prefix=flower
    depends_on:
      - celery
  redmon:  #  Redis monitoring
    build: ./docker/redmon/
    command: redmon --port=4567 --redis=redis://redis --base-path=/redmon --secure=${REDMON_BASIC_AUTH}
    depends_on:
      - redis