# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclient',
            name='agree_tos',
            field=models.BooleanField(default=False),
        ),
    ]
