# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_apiclient_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='password_grant_is_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
