# Generated by Django 2.2.10 on 2020-02-06 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apiclient_password_grant_is_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apiclient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_apiclient', to=settings.AUTH_USER_MODEL),
        ),
    ]
