from api.constants import *

# Some of these concept definitions should be linked with the ontology (or be loaded from it)
AUDIOCOMMONS_ONTOLOGY_PREFIX = 'ac:'

# Component names
SEARCH_TEXT_COMPONENT = 'text_search'
LICENSING_COMPONENT = 'licensing'

# Authentication
APIKEY_AUTH_METHOD = 'apikey_auth'
ENDUSER_AUTH_METHOD = 'enduser_auth'

# Resource fields (just using fake names here)
FIELD_ID = AUDIOCOMMONS_ONTOLOGY_PREFIX + 'id'
FIELD_URL = AUDIOCOMMONS_ONTOLOGY_PREFIX + 'url'
FIELD_NAME = AUDIOCOMMONS_ONTOLOGY_PREFIX + 'name'
FIELD_LICENSE = AUDIOCOMMONS_ONTOLOGY_PREFIX + 'license'
FIELD_AUTHOR_NAME = AUDIOCOMMONS_ONTOLOGY_PREFIX + 'author_name'
FIELD_TAGS = AUDIOCOMMONS_ONTOLOGY_PREFIX + 'tags'
FIELD_STATIC_RETRIEVE = AUDIOCOMMONS_ONTOLOGY_PREFIX + 'static_retrieve'
FIELD_DURATION = AUDIOCOMMONS_ONTOLOGY_PREFIX + 'duration'
FIELD_FILESIZE = AUDIOCOMMONS_ONTOLOGY_PREFIX + 'filesize'
FIELD_CHANNELS = AUDIOCOMMONS_ONTOLOGY_PREFIX + 'channels'
FIELD_BITRATE = AUDIOCOMMONS_ONTOLOGY_PREFIX + 'bitrate'
FIELD_BITDEPTH = AUDIOCOMMONS_ONTOLOGY_PREFIX + 'bitdepth'
FIELD_SAMPLERATE = AUDIOCOMMONS_ONTOLOGY_PREFIX + 'samplerate'
FIELD_TYPE = AUDIOCOMMONS_ONTOLOGY_PREFIX + 'type'

MINIMUM_RESOURCE_DESCRIPTION_FIELDS = [
    FIELD_ID,
    FIELD_URL,
    FIELD_NAME,
    FIELD_AUTHOR_NAME,
    FIELD_LICENSE,
    FIELD_STATIC_RETRIEVE
]

# Search results parameters
NEXT_PAGE_PROP = 'next'
PREV_PAGE_PROP = 'prev'
NUM_RESULTS_PROP = 'num_results'
RESULTS_LIST = 'results'

# Sort options
SORT_OPTION_RELEVANCE = 'relevance'
SORT_OPTION_POPULARITY = 'popularity'
SORT_OPTION_DURATION = 'duration'
SORT_OPTION_DOWNLOADS = 'downloads'
SORT_OPTION_CREATED = 'created'

SORT_OPTIONS = [
    SORT_OPTION_RELEVANCE,
    SORT_OPTION_POPULARITY,
    SORT_OPTION_DURATION,
    SORT_OPTION_DOWNLOADS,
    SORT_OPTION_CREATED,
]

# Licenses
LICENSE_UNKNOWN = 'Unknown'
LICENSE_CC0 = 'CC0'
LICENSE_CC_BY = 'BY'
LICENSE_CC_BY_SA = 'BY-SA'
LICENSE_CC_BY_NC = 'BY-NC'
LICENSE_CC_BY_ND = 'BY-ND'
LICENSE_CC_BY_NC_SA = 'BY-NC-SA'
LICENSE_CC_BY_NC_ND = 'BY-NC-ND'
LICENSE_CC_SAMPLING_PLUS = 'Sampling+'
