# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161025_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accepted_tos',
            field=models.BooleanField(default=False),
        ),
    ]
