# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_accepted_tos'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecredentials',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
