# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_servicecredentials_created'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicecredentials',
            unique_together=set([('account', 'service_id')]),
        ),
    ]
