# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 14:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_servicecredentials_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecredentials',
            name='credentials',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None),
        ),
    ]
