# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 14:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20161027_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecredentials',
            name='credentials',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
