# Generated by Django 2.2.10 on 2020-02-06 15:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20161027_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='servicecredentials',
            name='credentials',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
